GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHJpc2hpIiwiaWF0IjoxNzI4MTgxOTkwfQ.0-hbUGzq-oOCO04adxuC2YUqsAioQ9XekXqFlpTaHh4
###

POST http://localhost:4000/token Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}


###


POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "hrishi"
}